spring:
  application:
    name: yu-ai-code-service
server:
  port: 8123
  servlet:
    context-path: /yu-ai-code

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.example.yuaicoder.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
